package com.jiahan.fave.database

import androidx.lifecycle.LiveData
import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query

@Dao
interface MovieDAO {

    @Query("select * from databasemovie")
    fun getMovies(): LiveData<List<DatabaseMovie>>

    @Query("select * from databasemovie")
    fun getMoviesPaging(): PagingSource<Int, DatabaseMovie>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertMovies(vararg movies: DatabaseMovie)

    @Query("delete from databasemovie")
    suspend fun deleteMovies()

    /**
     * So that autogenerated key for DatabaseMovie table will start from 1
     */
    @Query("delete from sqlite_sequence where name='DatabaseMovie'")
    suspend fun deleteSequence()
}
