package com.jiahan.fave.database

import androidx.lifecycle.LiveData
import androidx.paging.PagingSource
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query

@Dao
interface MovieDAO {

    @Query("select * from movies")
    fun getMovies(): LiveData<List<Movie>>

    @Query("select * from movies")
    fun getMoviesPaging(): PagingSource<Int, Movie>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertMovies(vararg movies: Movie)

    @Query("delete from movies")
    suspend fun deleteMovies()

    /**
     * Remove the value so that autogenerated key for Movie table will not accumulated
     */
    @Query("delete from sqlite_sequence where name='Movie'")
    suspend fun deleteSequence()
}